name: demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
